import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
// import.meta.url shim — esbuild's CJS output stubs import.meta to {}, but
// @anthropic-ai/claude-agent-sdk calls createRequire(import.meta.url) at module
// scope, which throws on undefined and prevents the whole plugin from loading.
var __import_meta_url = typeof __filename !== "undefined"
	? require("node:url").pathToFileURL(__filename).href
	: "file:///main.js";
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
		...builtinModules.map((m) => `node:${m}`)],
	format: "cjs",
	define: {
		"import.meta.url": "__import_meta_url",
	},
	loader: {
		".svg": "text",
	},
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "../large-language-models/main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}