export const claude = "claude"
export const openAI = "openAI"
export const gemini = "gemini"
export const GPT4All = "GPT4All"

export const claudeSonnetJuneModel = "claude-3-5-sonnet-20240620"
export const geminiModel = "gemini-1.5-flash"
export const gemini2FlashModel = "gemini-2.0-flash-exp"
export const gemini2FlashThinkingModel = "gemini-2.0-flash-thinking-exp-1219"
export const gemini2FlashStableModel = "gemini-2.0-flash"
export const gemini2FlashLiteModel = "gemini-2.0-flash-lite"
export const gemini25ProModel = "gemini-2.5-pro"
export const gemini25FlashModel = "gemini-2.5-flash"
export const gemini25FlashLiteModel = "gemini-2.5-flash-lite"
export const gemini3ProPreviewModel = "gemini-3-pro-preview"
export const geminiFlashLatestModel = "gemini-flash-latest"
export const geminiFlashLiteLatestModel = "gemini-flash-lite-latest"
export const openAIModel = "gpt-3.5-turbo"

export const messages = "messages"
export const assistant = "assistant"
export const chat = "chat"
